### ISSUE TITLE
sdt-guide sorun yaratabilir @bufgix

### ISSUE THREAD

**Issue by omerayyildiz** [sdtrdev/sdtr-guide#4]
https://github.com/sdtrdev/sdtr-guide/blob/6e42cb93df0198c5cf9846968a21c26721c7b89e/sdturkey/index.js#L18

**Comment by omerayyildiz** [comment]
@bufgix

**Comment by bufgix** [comment]
o stringi  `https://github.com/sdtrdev/sdtr-guide/blob/master/info.json` ile değiştirebilirsin. Böylece benim sürekli update etmem gerek kalmaz

**Comment by omerayyildiz** [comment]
Okeydir. Halletim 👍🏻
